# Generated by Django 5.0.6 on 2024-06-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbers',
            name='status',
            field=models.CharField(default=12, max_length=50, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
