# Generated by Django 5.0.6 on 2024-06-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_numbers_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbers',
            name='price',
            field=models.TextField(default=123, verbose_name='Стоимость'),
            preserve_default=False,
        ),
    ]
