# Generated by Django 5.0.6 on 2024-06-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_numbers_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleB', models.CharField(max_length=50, verbose_name='Номер')),
                ('guest', models.TextField(verbose_name='Гость')),
                ('begin_date', models.DateField(verbose_name='Дата начала бронирования')),
                ('end_date', models.DateField(verbose_name='Дата окончания бронирования')),
            ],
        ),
        migrations.CreateModel(
            name='BookService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_service', models.TextField(verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование')),
                ('guest', models.TextField(verbose_name='Гость')),
                ('service_date', models.TextField(verbose_name='Дата оказания')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('sex', models.TextField(verbose_name='Пол')),
                ('passport', models.TextField(verbose_name='Паспортные данные')),
                ('status', models.TextField(verbose_name='Статус')),
                ('species', models.TextField(verbose_name='Особенности')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_service', models.TextField(verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование')),
                ('price', models.TextField(verbose_name='Стоимость')),
                ('duration', models.TextField(verbose_name='Продолжительность')),
            ],
        ),
        migrations.RemoveField(
            model_name='numbers',
            name='number',
        ),
        migrations.AddField(
            model_name='numbers',
            name='count_person',
            field=models.TextField(default=123, verbose_name='Местность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numbers',
            name='count_rooms',
            field=models.TextField(default=123, verbose_name='Количество комнат'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numbers',
            name='room_type',
            field=models.TextField(default=123, verbose_name='Класс номера'),
            preserve_default=False,
        ),
    ]
