# Generated by Django 5.0.6 on 2024-06-10 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_booking_bookservice_person_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='titleB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='main.numbers', verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='status',
            field=models.CharField(choices=[('free', 'Свободен'), ('occupied', 'Занят')], default='free', max_length=20, verbose_name='Статус'),
        ),
    ]
