# Generated by Django 5.0.6 on 2024-06-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_booking_titleb_alter_numbers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookservice',
            name='id_service',
            field=models.IntegerField(verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bookservice',
            name='service_date',
            field=models.DateField(verbose_name='Дата оказания'),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='count_person',
            field=models.IntegerField(verbose_name='Местность'),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='count_rooms',
            field=models.IntegerField(verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='status',
            field=models.CharField(choices=[('free', 'Свободен'), ('occupied', 'Занят')], default='Свободен', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='person',
            name='passport',
            field=models.IntegerField(verbose_name='Паспортные данные'),
        ),
        migrations.AlterField(
            model_name='services',
            name='id_service',
            field=models.IntegerField(verbose_name='ID'),
        ),
    ]
