# Generated by Django 5.0.6 on 2024-06-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_bookservice_id_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('O', 'Обычный'), ('V', 'ВИП')], max_length=1, verbose_name='Статус'),
        ),
    ]
