# Generated by Django 5.0.6 on 2024-06-12 00:02

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_person_sex_alter_person_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='passport',
            field=models.CharField(max_length=11, validators=[main.validators.validate_passport], verbose_name='Паспортные данные'),
        ),
    ]
