# Generated by Django 5.0.6 on 2024-06-19 10:16

import django.db.models.deletion
import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_booking_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Номер')),
                ('room_type', models.TextField(verbose_name='Класс номера')),
                ('price', models.TextField(verbose_name='Стоимость в баксах')),
                ('count_rooms', models.IntegerField(verbose_name='Количество комнат')),
                ('count_person', models.IntegerField(verbose_name='Местность')),
                ('status', models.CharField(choices=[('free', 'Свободен'), ('occupied', 'Занят')], max_length=20, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='FilterPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('sex', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('passport', models.CharField(max_length=11, validators=[main.validators.validate_passport], verbose_name='Паспортные данные')),
                ('status', models.CharField(choices=[('O', 'Обычный'), ('V', 'ВИП')], max_length=1, verbose_name='Статус')),
                ('species', models.TextField(verbose_name='Особенности')),
            ],
        ),
        migrations.AlterField(
            model_name='numbers',
            name='price',
            field=models.TextField(verbose_name='Стоимость в баксах'),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='status',
            field=models.CharField(choices=[('free', 'Свободен'), ('occupied', 'Занят')], max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='FilterBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField(verbose_name='Дата начала бронирования')),
                ('end_date', models.DateField(verbose_name='Дата окончания бронирования')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filterBookings', to='main.person', verbose_name='Гость')),
                ('titleB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filerBookings', to='main.numbers', verbose_name='Номер')),
            ],
        ),
    ]
