# Generated by Django 5.0.6 on 2024-06-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_filternumbers_filterperson_alter_numbers_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='duration',
            field=models.DurationField(verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.IntegerField(verbose_name='Стоимость'),
        ),
    ]
