# Generated by Django 5.0.6 on 2024-06-19 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_services_duration_alter_services_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateTimeField(verbose_name='Дата и время оказания услуги')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to='main.person', verbose_name='Гость')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='main.services', verbose_name='Услуга')),
            ],
        ),
        migrations.DeleteModel(
            name='BookService',
        ),
    ]
